# Generated by Django 5.1.2 on 2024-11-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
