# Generated by Django 5.1.2 on 2024-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default-avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
